### ISSUE TITLE
Crash with electron

### ISSUE THREAD

**Issue by sebastiencs** [mbrubeck/mediumvec#7]
Hi, thanks for this package.

I've tried to use it with my electron app and it makes it crash.
It occurs when I use `push` on a vector that already have an item.
It seems that it is caused by the allocator. I have this error: 

```
../../third_party/tcmalloc/chromium/src/free_list.h:72] Circular loop in list detected:  0x15bed2d73cc0 
```
[source](https://chromium.googlesource.com/chromium/src/third_party/tcmalloc/chromium/+/master/src/free_list.h#72)

Backtrace:
```
(gdb) bt
#0  0x0000000001f717a0 in  ()
#1  0x0000000001f6b950 in  ()
#2  0x0000000001f6f2a7 in  ()
#3  0x0000000004f2ca5d in __start_google_malloc ()
#4  0x0000000001ff1c65 in realloc ()
#5  0x00007fffdbcffd96 in <alloc::alloc::Global as core::alloc::GlobalAlloc>::realloc (self=0x7fffdb1b3d30, ptr=0x39a1edc1c9d0, layout=..., new_size=32)
at /checkout/src/liballoc/alloc.rs:95
#6  0x00007fffdbcffb5d in <alloc::alloc::Global as core::alloc::Alloc>::realloc (self=0x7fffdb1b3d30, ptr=..., layout=..., new_size=32)
at /checkout/src/liballoc/alloc.rs:140
#7  0x00007fffdbd3bba0 in <alloc::raw_vec::RawVec<T, A>>::try_reserve_exact (self=0x7fffdb1b3d30, used_cap=1, needed_extra_cap=1)
at /checkout/src/liballoc/raw_vec.rs:430
#8  0x00007fffdbd3a575 in <alloc::raw_vec::RawVec<T, A>>::reserve_exact (self=0x7fffdb1b3d30, used_cap=1, needed_extra_cap=1)
at /checkout/src/liballoc/raw_vec.rs:443
#9  0x00007fffdbd1aa70 in <alloc::vec::Vec<T>>::reserve_exact (self=0x7fffdb1b3d30, additional=1) at /checkout/src/liballoc/vec.rs:490
#10 0x00007fffdbd59fdc in <mediumvec::vec32::Vec32<T>>::reserve_exact::{{closure}} (v=0x7fffdb1b3d30) at /home/sebastien/github/mediumvec/src/vec32.rs:201
#11 0x00007fffdbd5a1ee in <mediumvec::vec32::Vec32<T>>::as_vec (self=0x7fffdb1b3f60, f=...) at /home/sebastien/github/mediumvec/src/vec32.rs:252
#12 0x00007fffdbd59fa7 in <mediumvec::vec32::Vec32<T>>::reserve_exact (self=0x7fffdb1b3f60, additional=1) at /home/sebastien/github/mediumvec/src/vec32.rs:201
#13 0x00007fffdbd5a363 in <mediumvec::vec32::Vec32<T>>::reserve (self=0x7fffdb1b3f60, additional=1) at /home/sebastien/github/mediumvec/src/vec32.rs:192
#14 0x00007fffdbd5a093 in <mediumvec::vec32::Vec32<T>>::push (self=0x7fffdb1b3f60, value=...) at /home/sebastien/github/mediumvec/src/vec32.rs:99
#15 0x00007fffdbd00485 in my_app::elf::Line::from_instuction (base=..., bytes=..., ins=0x7fffdb1b4270, jmp=..., strings=0x39a1eb736308)
at src/elf/mod.rs:245
(gdb) 
```

I made a small repo to reproduce the crash: https://github.com/sebastiencs/crash_mediumvec

Let me know if you need more informations. Thanks !

**Comment by mbrubeck** [comment]
Fixed by #5.
